<div class="page-header">
    <h1 class="pull-left">Редактирование бренда</h1>
    <div class="clearfix"></div>
</div>
<div class="clearfix"></div>
<form method="post" id="form_id">
    <input type="hidden" value="<?=$this->brand_id?>" name="brand_id">
    <div class="col-sm-6">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label " for="brand_name">Наименование</label>
                <input type="text" id="brand_name" placeholder="Наименование" class="form-control" value="<?=$this->row['brand_name']?>" name="brand_name">
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label " for="brand_code">Код</label>
                <input type="text" id="brand_code" placeholder="Код" class="form-control" value="<?=$this->row['brand_code']?>" name="brand_code">
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label " for="order_num">Порядковый номер</label>
                <input type="text" id="order_num" placeholder="Код" class="form-control" value="<?=$this->row['order_num']?>" name="order_num">
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
        <button type="submit" class="btn btn-sm btn-success">
            <i class="ace-icon fa fa-check"></i>
            Сохранить
        </button>
        <a href="/dict/brand-list/">
            <button type="button" class="btn btn-sm btn-danger">
                <i class="ace-icon fa fa-arrow-left"></i>
                Назад
            </button>
        </a>
    </div>

</form>