<div class="widget-box loading-widget" id="sh_module_widget">
    <div class="widget-header">
        <h4 class="widget-title">Категории</h4>
        <div class="widget-toolbar">
            <a data-action="collapse" href="#">
                <i class="ace-icon fa fa-chevron-up"></i>
            </a>
        </div>
    </div>
    <div class="widget-body" style="display: block;">
        <div class="widget-main">
            <div class="table-responsive">
                <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
                    <input type="hidden" name="reload_type" id="reload_type">
                    <thead>
                    <tr>
                        <th>Наименование</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?
                    if(count($this->row) > 0){
                        foreach ($this->row as $key => $value){
                            ?>
                            <tr onclick="stackCategoryUpd(<?=$value['category_id']?>, this)" <?if($value['is_checked'] == 1){?> class="selected-td" <?}?>>
                                <td class="text-left"><?=$value['category_name']?></td>
                            </tr>
                            <?
                        }
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>