<div class="page-header">
    <h1 class="pull-left">Ведение категории</h1>
    <ul class="list-unstyled spaced list-inline pull-right no-margin-bottom">
        <li class="no-margin">
            <div class="action-buttons">
                <a class="green" href="javascript:void(0);">
                    <i class="ace-icon fa fa-circle-o bigger-130"></i>
                </a>
                Изменить активность
            </div>
        </li>
        <li class="no-margin">
            <div class="action-buttons">
                <a class="red" href="javascript:void(0);">
                    <i class="ace-icon fa fa-trash-o bigger-130"></i>
                </a>
                Удаление категории
            </div>
        </li>
    </ul>
    <div class="clearfix"></div>
</div>
<div class="clearfix"></div>
<div class="btns-block pull-right">
    <a href="/dict/category-edit/category_id/0" class="btn btn-xs btn-primary" >Добавить категорию</a>
</div>
<div class="clearfix"></div>
<div class="hr hr-10 dotted hr-double"></div>
<div class="table-responsive">
    <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
        <thead>
        <tr>
            <th>ID</th>
            <th>Наименование</th>
            <th>Код</th>
            <th>Порядковый номер</th>
            <th>Активный</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?
        if(count($this->row) > 0){
            foreach ($this->row as $key => $value){?>
                <tr>
                    <td class="text-right"><?=$value['category_id']?></td>
                    <td class="text-left"><a href="/dict/category-edit/category_id/<?=$value['category_id']?>/"><?=$value['category_name']?></a></td>
                    <td class="text-left"><?=$value['category_code']?></td>
                    <td class="text-center"><?=$value['order_num']?></td>
                    <td class="text-center">
                        <?
                        if($value['is_show'] > 0){?>
                            <a class="red" href="javascript:void(0);" onclick="showUpd(<?=$value['category_id']?>)">
                                <i class="ace-icon fa fa-ban bigger-130"></i>
                            </a>
                            <?
                        }else{?>
                            <a class="green" href="javascript:void(0);" onclick="showUpd(<?=$value['category_id']?>)">
                                <i class="ace-icon fa fa-circle-o bigger-130"></i>
                            </a>
                            <?
                        }?>
                    </td>
                    <td>
                        <div class="text-center">
                            <a class="red" href="javascript:void(0);" onclick="delCategory(<?=$value['category_id']?>, this)">
                                <i class="ace-icon fa fa-trash-o bigger-130"></i>
                            </a>
                        </div>
                    </td>
                </tr>
                <?
            }
        }
        ?>
        </tbody>
    </table>
</div>


<script>
    $(document).ready(function() {

    });

    function showUpd(category_id){
        if (!confirm("Вы действительно хотите изменить активность категории?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/dict/category-list/mode/show-upd/category_id/" + category_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    Notify.generate('Ошибка', '', 3);
                }
                else{
                    Notify.generate('Активность изменен', '', 1);
                    location.reload();
                }
            }
        });
    }

    function delCategory(category_id, ob){
        if (!confirm("Вы действительно хотите удалить категорию?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/dict/category-list/mode/del-category/category_id/" + category_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    Notify.generate('Ошибка', '', 3);
                }
                else{
                    Notify.generate('Категория удалена', '', 1);
                    $(ob).closest("tr").remove();
                }
            }
        });
    }
</script>