<div class="page-header">
    <h1 class="pull-left">Редактирование категории</h1>
    <div class="clearfix"></div>
</div>
<div class="clearfix"></div>
<form method="post" id="form_id">
    <input type="hidden" value="<?=$this->category_id?>" name="category_id">
    <div class="col-sm-6">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label " for="category_name">Наименование</label>
                <input type="text" id="category_name" placeholder="Наименование" class="form-control" value="<?=$this->row['category_name']?>" name="category_name">
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label " for="category_code">Код</label>
                <input type="text" id="category_code" placeholder="Код" class="form-control" value="<?=$this->row['category_code']?>" name="category_code">
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label " for="order_num">Порядковый номер</label>
                <input type="text" id="order_num" placeholder="Код" class="form-control" value="<?=$this->row['order_num']?>" name="order_num">
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label" for="brand_id">Тип</label>
                <div class="form-control no-padding">
                    <select class="form-control" id="product_type_id" name="product_type_id">
                        <option value="0">Выберите тип</option>
                        <?
                        if(count($this->type_list) > 0){
                            foreach($this->type_list as $key => $value){?>
                                <option value="<?=$value['product_type_id']?>" <?if($this->row['product_type_id'] == $value['product_type_id']){echo ' selected';}?>><?=$value['product_type_name']?></option>
                                <?
                            }
                        }?>
                    </select>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <button type="submit" class="btn btn-sm btn-success">
            <i class="ace-icon fa fa-check"></i>
            Сохранить
        </button>
        <a href="/dict/category-list/">
            <button type="button" class="btn btn-sm btn-danger">
                <i class="ace-icon fa fa-arrow-left"></i>
                Назад
            </button>
        </a>
    </div>

</form>