<div class="page-header">
    <h1 class="pull-left">Ведение лотов</h1>
    <div class="btns-block pull-left">
        <a href="/dict/lot-edit/lot_id/0/" class="btn btn-xs btn-primary" >Добавить лот</a>
    </div>
    <ul class="list-unstyled spaced list-inline pull-right no-margin-bottom">
        <li class="no-margin">
            <div class="action-buttons">
                <a class="red" href="javascript:void(0);">
                    <i class="ace-icon fa fa-trash-o bigger-130"></i>
                </a>
                Удаление
            </div>
        </li>
    </ul>
    <ul class="list-unstyled spaced list-inline pull-right no-margin-bottom">
        <li class="no-margin">
            <div class="action-buttons">
                <a class="green" href="javascript:void(0);">
                    <?if($this->is_active == 1){?>
                        <i class="ace-icon fa fa-circle-o bigger-130"></i>
                    <?}else{?>
                        <i class="ace-icon fa fa-circle bigger-130"></i>
                    <?}?>
                </a>
                Изменить активность
            </div>
        </li>
    </ul>
    <div class="clearfix"></div>
</div>
<div class="clearfix"></div>

<form id="form1">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6" style="">
        <div class="col-lg-8 col-md-6 col-sm-6 col-xs-12">
            <label class="control-label">По периоду</label>
            <div class="clearfix"></div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style="padding-left: 0;">
                <input class="form-control date-picker" type="text" name="date_begin" id="start_date" placeholder="С" data-date-format="dd/mm/yyyy" autocomplete="off" value="<?=$this->date_begin?>">
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style="padding-right: 0;">
                <input class="form-control date-picker" type="text" name="date_end" id="end_date" placeholder="По" data-date-format="dd/mm/yyyy" autocomplete="off" value="<?=$this->date_end?>">
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-4 col-xs-12">
            <label class="control-label">Товар</label>
            <div class="clearfix"></div>
            <input type="text" class="form-control" name="product_name" value="<?=$this->product_name?>" placeholder="Товар"  autocomplete="off">
        </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12" style="margin-top: 26px;">
        <a>
            <button type="submit" class="btn btn-sm btn-primary" name="submit" ">
            <i class="ace-icon fa fa-search"></i>
            Поиск
            </button>
        </a>
        <a href="/dict/lot-list/">
            <button type="button" class="btn btn-sm btn-primary" name="resetSearch"">
            <i class="ace-icon fa fa-refresh"></i>
            Сбросить
            </button>
        </a>
    </div>
</form>
<div class="clearfix"></div>
<div class="hr hr-10 dotted hr-double"></div>
<div class="table-responsive">
    <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
        <thead>
        <tr>
            <th>ID</th>
            <th>Товар</th>
            <th>Кол-во</th>
            <th>Дата лота</th>
            <th>Оператор</th>
            <th>Дата добавления</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?
            echo $this->partialLoop('dict/lot-list-form.phtml', $this->paginator);
        ?>
        </tbody>
    </table>
    <div style="float: right">
        <?=$this->paginationControl($this->paginator, 'Sliding', 'dict/pagination.phtml');?>
    </div>
</div>


<div id="modal" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header no-padding">
                <div class="table-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        <span class="white">&times;</span>
                    </button>
                    Редактирование лота
                </div>
            </div>
            <div id="modal_body"></div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>


<script>
    $(document).ready(function() {

    });

    function delLot(lot_id, ob){
        if (!confirm("Вы действительно хотите удалить лот?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/dict/lot-list/mode/delete/lot_id/" + lot_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    Notify.generate('Ошибка', '', 3);
                }
                else{
                    Notify.generate('Лот успешно удален', '', 1);
                    $(ob).closest("tr").remove();
                }
            }
        });
    }
    function is_active_upd(lot_id, is_active, amount, product_id, ob){
        if (!confirm("Вы действительно хотите изменить активность?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/dict/lot-list/mode/is-active/lot_id/" + lot_id + "/is_active/" + is_active + "/amount/" + amount +"/product_id/"+ product_id +"/",
            success: function(data){
                if(data.result['status'] == false){
                    Notify.generate('Ошибка', '', 3);
                }
                else{
                    Notify.generate('Лот успешно перенесен', '', 1);
                    $(ob).closest("tr").remove();
                }
            }
        });
    }
    function lotEdit(lot_id){
        $("#modal_body").empty();
        $.ajax({
            type: 'POST',
            url: "/dict/lot-edit/lot_id/" + lot_id + "/",
            async: true,
            success: function(data){
                $("#modal_body").html(data);
            }
        });
        $(".modal").modal('show');
    }
</script>