<div class="page-header">
    <h1 class="pull-left">Редактирование лота</h1>
    <div class="clearfix"></div>
</div>
<div class="clearfix"></div>
<form method="post" id="form_id">
    <input type="hidden" value="<?=$this->lot_id?>" name="lot_id">
    <div class="col-sm-6">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label" for="new_product_add">Товар</label>
                <input type="text" id="new_product_input" name="new_product_add" class="ui-autocomplete-input" autocomplete="off" value="<?=$this->row['product_name']?>" style="float: left; width: 424px;" onkeypress="checkProductSelected()" onkeyup="checkProductSelected()">
                <input type="hidden" name="product_id" id="product_id" value="<?=$this->row['product_id']?>">
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label " for="fio">Количество</label>
                <input type="text" id="amount" placeholder="Количество" class="form-control" name="amount" value="<?=$this->row['amount']?>">
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label " for="order_num">Дата</label>
                <input class="form-control date-picker" type="text" name="lot_date" id="lot_date" placeholder="Дата" data-date-format="dd/mm/yyyy" autocomplete="off" value="<?=$this->row['lot_date']?>">
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
        <button type="submit" class="btn btn-sm btn-success">
            <i class="ace-icon fa fa-check"></i>
            Сохранить
        </button>
        <a href="/dict/category-list/">
            <button type="button" class="btn btn-sm btn-danger">
                <i class="ace-icon fa fa-arrow-left"></i>
                Назад
            </button>
        </a>
    </div>

</form>
<form method="post" id="form_id">
    <input type="hidden" value="<?=$this->lot_id?>" name="lot_id">
    <div class="col-sm-12">
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>

    <div class="clearfix"></div>
</form>
<script>
    function updAmount() {
        var send_data = $('#form_id').serializeArray();
        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/dict/product-list/mode/upd-amount/",
            success: function(data){
                if(data.result['status'] == false){
                    Notify.generate('Ошибка', '', 3);
                }
                else{
                    Notify.generate('Товар добавлен', '', 1);
                    $(".modal").modal('hide');
                    // stackListForm();
                }
            }
        });
    }
    function checkProductSelected(){
        var new_product_input_len = myTrim($("#new_product_input").val());
        // if(new_product_input_len.length > 0){
        // }
        // else{
        //     $("#product_id").attr("value","");
        // }
    }

    function myTrim(x) {
        return x.replace(/^\s+|\s+$/gm,'');
    }
    $("#new_product_input").autocomplete({
        source: function( request, response ) {
            city_id = 0;
            $.ajax({
                url: "/dict/lot-edit/mode/get-products/",
                data: {
                    product_name: request.term
                },
                success: function( data ) {
                    response( $.map( data.product_list, function( item ) {
                        return {
                            label: item.product_name,
                            value: item.product_name,
                            key: item.product_id
                        }
                    }));
                }
            });
        },
        minLength: 2,
        select: function( event, ui ) {
            $("#product_id").val(ui.item.key);
            $(this).val(ui.item.label);
            return false;
        }
    });
</script>