<tr>
    <td class="text-right"><?=$this->lot_id?></td>
    <td class="text-left"><a href="/dict/lot-edit/lot_id/<?=$this->lot_id?>/"><?=$this->product_name?></a></td>
    <td class="text-right"><?=$this->amount?></td>
    <td class="text-center"><?=$this->lot_date?></td>
    <td class="text-left"><?=$this->fio?></td>
    <td class="text-center"><?=$this->rowversion?></td>
    <td>
        <div class="text-center">
            <a class="red" href="javascript:void(0);" onclick="delLot(<?=$this->lot_id?>, this)">
                <i class="ace-icon fa fa-trash-o bigger-130"></i>
            </a>
        </div>
    </td>
</tr>