<style>
    .myPaginator{
        display: inline-block;
        margin-top: 15px;
    }
    .myPaginator a {
        color: black;
        float: left;
        padding: 5px 10px;
        text-decoration: none;
        transition: background-color .3s;
        border: 1px solid #ddd;
        font-size: 12px;
    }

    .myPaginator a.active {
        background-color: #0e90d2;
        color: white;
        border: 1px solid #0e90d2;
    }
    li {
        list-style-type: none; /* Убираем маркеры */
    }

    .myPaginator a:hover:not(.active) {background-color: #ddd;}
</style>
<?
$params = ($_SERVER['REQUEST_URI']!=$this->baseUrl()) ? str_replace($this->baseUrl()."/","",$_SERVER['REQUEST_URI']) : $_SERVER['REQUEST_URI'] ;
$params = explode("?",$params);
if (empty($params[1]))
    $get = "";
else
    $get = "?".$params[1];
?>
<div class="myPaginator">
    <ul>
        <!-- Previous page link -->
        <? if (isset($this->previous)): ?>
            <a href="<?= $this->url(array('page' => $this->previous)) .$get; ?>"><i class="fa fa-angle-double-left"></i></a>
        <? else: ?>
            <a href="#"><i class="fa fa-angle-double-left"></i></a>
        <? endif; ?>
        <!-- Numbered page links -->
        <? foreach ($this->pagesInRange as $page): ?>
            <? if ($page != $this->current): ?>
               <a href="<?= $this->url(array('page' => $page)).$get; ?>"><?= $page; ?></a>
            <? else: ?>
                <a class="active" href="#"><?= $page; ?></a>
            <? endif; ?>
        <? endforeach; ?>
        <!-- Next page link -->
        <? if (isset($this->next)): ?>
            <a href="<?= $this->url(array('page' => $this->next)) . $get; ?>"><i class="fa fa-angle-double-right"></i></a>
        <? else: ?>
            <a href="#"><i class="fa fa-angle-double-right"></i></a>
        <? endif; ?>
    </ul>
</div>