<div class="page-header">
    <h1 class="pull-left">Редактирование товара</h1>
    <div class="clearfix"></div>
</div>
<div class="clearfix"></div>
<form method="post" id="form_id">
    <input type="hidden" value="<?=$this->product_id?>" name="product_id">
    <div class="col-sm-6">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label " for="brand_name">Наименование</label>
                <input type="text" id="product_name" placeholder="Наименование" class="form-control" value="<?=$this->row['product_name']?>" name="product_name">
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label" for="category_id">Категория</label>
                <div class="form-control no-padding">
                    <select class="form-control" id="category_id" name="category_id">
                        <option value="0">Выберите категорию</option>
                        <?
                        if(count($this->category_list) > 0){
                            foreach($this->category_list as $key => $value){?>
                                <option value="<?=$value['category_id']?>" <?if($this->row['category_id'] == $value['category_id']){echo ' selected';}?>><?=$value['category_name']?></option>
                                <?
                            }
                        }?>
                    </select>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label" for="brand_id">Бренд</label>
                <div class="form-control no-padding">
                    <select class="form-control" id="brand_id" name="brand_id">
                        <option value="0">Выберите бренд</option>
                        <?
                        if(count($this->brand_list) > 0){
                            foreach($this->brand_list as $key => $value){?>
                                <option value="<?=$value['brand_id']?>" <?if($this->row['brand_id'] == $value['brand_id']){echo ' selected';}?>><?=$value['brand_name']?></option>
                                <?
                            }
                        }?>
                    </select>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <button type="submit" class="btn btn-sm btn-success">
            <i class="ace-icon fa fa-check"></i>
            Сохранить
        </button>
        <a href="/dict/product-list/">
            <button type="button" class="btn btn-sm btn-danger">
                <i class="ace-icon fa fa-arrow-left"></i>
                Назад
            </button>
        </a>
    </div>

</form>