<div class="modal-body" id="modal_body">
    <form method="post" id="form_id">
        <input type="hidden" value="<?=$this->product_id?>" name="product_id">
        <div class="col-sm-12">
            <div class="form-group">
                <label class="control-label " for="fio">Количество</label>
                <input type="text" id="amount" placeholder="Количество" class="form-control" name="amount">
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer no-margin-top">
    <button type="button" class="btn btn-sm btn-success" name="upd_amount" onclick="updAmount()">
        <i class="ace-icon fa fa-check"></i>
        Сохранить
    </button>
    <button class="btn btn-sm btn-danger" data-dismiss="modal">
        <i class="ace-icon fa fa-times"></i>
        Закрыть
    </button>
</div>
<script>
    function updAmount() {
        var send_data = $('#form_id').serializeArray();
        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/dict/product-list/mode/upd-amount/",
            success: function(data){
                if(data.result['status'] == false){
                    Notify.generate('Ошибка', '', 3);
                }
                else{
                    Notify.generate('Товар добавлен', '', 1);
                    $(".modal").modal('hide');
                    // stackListForm();
                }
            }
        });
    }
</script>