<div class="table-responsive">
    <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
        <thead>
        <tr>
            <th>ID</th>
            <th>Наименование</th>
            <th>Цена</th>
            <th>Кол-во</th>
            <th>Штрих-код</th>
            <th>Категория</th>
            <th>Бренд</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?
        if(count($this->row) > 0){
            foreach ($this->row as $key => $value){?>
                <tr>
                    <td class="text-right"><?=$value['product_id']?></td>
                    <td class="text-left"><a href="/dict/product-edit/product_id/<?=$value['product_id']?>/"><?=$value['product_name']?></a></td>
                    <td class="text-right"><?=tenge_text($value['price'])?></td>
                    <td class="text-right"><?=$value['cnt']?></td>
                    <td class="text-center"><?=$value['barcode']?></td>
                    <td class="text-left"><?=$value['category_name']?></td>
                    <td class="text-left"><?=$value['brand_name']?></td>
                    <td>
                        <div class="text-center">
                            <a class="blue" href="javascript:void(0);" onclick="addCnt(<?=$value['product_id']?>, this)">
                                <i class="ace-icon fa fa-plus-circle bigger-130"></i>
                            </a>
                        </div>
                    </td><td>
                        <div class="text-center">
                            <a class="red" href="javascript:void(0);" onclick="delProduct(<?=$value['product_id']?>, this)">
                                <i class="ace-icon fa fa-trash-o bigger-130"></i>
                            </a>
                        </div>
                    </td>
                </tr>
                <?
            }
        }
        ?>
        </tbody>
    </table>
</div>