<div class="page-header">
    <h1 class="pull-left">Ведение товаров</h1>
    <ul class="list-unstyled spaced list-inline pull-right no-margin-bottom">
        <li class="no-margin">
            <div class="action-buttons">
                <a class="green" href="javascript:void(0);">
                    <i class="ace-icon fa fa-circle-o bigger-130"></i>
                </a>
                Изменить активность
            </div>
        </li>
        <li class="no-margin">
            <div class="action-buttons">
                <a class="red" href="javascript:void(0);">
                    <i class="ace-icon fa fa-trash-o bigger-130"></i>
                </a>
                Удаление товара
            </div>
        </li>
    </ul>
    <div class="clearfix"></div>
</div>
<div class="clearfix"></div>
<div class="btns-block pull-right">
    <a href="/dict/product-edit/product_id/0/" class="btn btn-xs btn-primary" >Добавить товар</a>
</div>
<div class="clearfix"></div>
<div class="hr hr-10 dotted hr-double"></div>
<div class="table-responsive">
    <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
        <thead>
        <tr>
            <th>ID</th>
            <th>Наименование</th>
            <th>Кол-во</th>
            <th>Штрих-код</th>
            <th>Категория</th>
            <th>Бренд</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?
        if(count($this->row) > 0){
            foreach ($this->row as $key => $value){?>
                <tr>
                    <td class="text-right"><?=$value['product_id']?></td>
                    <td class="text-left"><a href="/dict/product-edit/product_id/<?=$value['product_id']?>/"><?=$value['product_name']?></a></td>
                    <td class="text-right"><?=$value['cnt']?></td>
                    <td class="text-left"><?=$value['barcode']?></td>
                    <td class="text-left"><?=$value['category_name']?></td>
                    <td class="text-left"><?=$value['brand_name']?></td>
                    <td>
                        <div class="text-center">
                            <a class="blue" href="javascript:void(0);" onclick="addCnt(<?=$value['product_id']?>, this)">
                                <i class="ace-icon fa fa-plus-circle bigger-130"></i>
                            </a>
                        </div>
                    </td><td>
                        <div class="text-center">
                            <a class="red" href="javascript:void(0);" onclick="delProduct(<?=$value['product_id']?>, this)">
                                <i class="ace-icon fa fa-trash-o bigger-130"></i>
                            </a>
                        </div>
                    </td>
                </tr>
                <?
            }
        }
        ?>
        </tbody>
    </table>
</div>


<div id="modal" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header no-padding">
                <div class="table-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        <span class="white">&times;</span>
                    </button>
                    Редактирование кол-во
                </div>
            </div>
            <div id="modal_body"></div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>


<script>
    $(document).ready(function() {

    });

    function delProduct(product_id, ob){
        if (!confirm("Вы действительно хотите удалить товар?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/dict/product-list/mode/delete/product_id/" + product_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    Notify.generate('Ошибка', '', 3);
                }
                else{
                    Notify.generate('Товар успешно удален', '', 1);
                    $(ob).closest("tr").remove();
                }
            }
        });
    }
    function addCnt(product_id){
        $("#modal_body").empty();
        $.ajax({
            type: 'POST',
            url: "/dict/product-cnt-edit/product_id/" + product_id + "/",
            async: true,
            success: function(data){
                $("#modal_body").html(data);
            }
        });
        $(".modal").modal('show');
    }
</script>