<div class="page-header">
    <h1 class="pull-left">Редактирование типа продукта</h1>
    <div class="clearfix"></div>
</div>
<div class="clearfix"></div>

<?php if(isset($this->error)){ ?>

    <div class="alert alert-danger">
        <p><?=$this->error?></p>
    </div>

<?}?>
<div class="clearfix"></div>
<form method="post" id="form_id">
    <input type="hidden" value="<?=$this->product_type_id?>" name="product_type_id">
    <div class="col-sm-6">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label " for="product_type_name">Наименование</label>
                <input type="text" id="product_type_name" placeholder="Наименование" class="form-control" value="<?=$this->row['product_type_name']?>" name="product_type_name">
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label " for="product_type_code">Код</label>
                <input type="text" id="product_type_code" placeholder="Код" class="form-control" value="<?=$this->row['product_type_code']?>" name="product_type_code">
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label " for="order_num">Порядковый номер</label>
                <input type="text" id="order_num" placeholder="Код" class="form-control" value="<?=$this->row['order_num']?>" name="order_num">
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
        <button type="submit" class="btn btn-sm btn-success">
            <i class="ace-icon fa fa-check"></i>
            Сохранить
        </button>
        <a href="/dict/product-type-list/">
            <button type="button" class="btn btn-sm btn-danger">
                <i class="ace-icon fa fa-arrow-left"></i>
                Назад
            </button>
        </a>
    </div>

</form>