<div class="page-header">
    <h1 class="pull-left">Редактирование товара:</h1>
    <a href="/dict/product-list/">
        <button type="button" class="btn btn-sm btn-primary" name="addProductHide" ">
        <i class="ace-icon fa fa-arrow-left"></i>
        Назад к списку
        </button>
    </a>
    <div class="clearfix"></div>
</div>
<ul class="nav nav-tabs" id="myTab">
    <li class="active">
        <a data-toggle="tab" href="#product_data">
            <i class="green fa fa-info-circle bigger-110"></i>
            Основные данные
        </a>
    </li>
    <?if(isset($this->row['product_id']) != 0){?>
        <li>
            <a data-toggle="tab" href="#characteristics1">
                <i class="green fa fa-cog bigger-110"></i>
                Доп. данные
            </a>
        </li>
    <?}?>
</ul>
<div class="clearfix"></div>

<div class="tab-content">
    <div id="product_data" class="tab-pane active">
        <form method="post" id="form_id">
            <input type="hidden" value="<?=$this->product_id?>" name="product_id">
            <div class="col-sm-6">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label " for="brand_name">Наименование</label>
                        <input type="text" id="product_name" placeholder="Наименование" class="form-control" value="<?=$this->row['product_name']?>" name="product_name">
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label" for="category_id">Категория</label>
                        <div class="form-control no-padding">
                            <select class="form-control" id="category_id" name="category_id">
                                <option value="0">Выберите категорию</option>
                                <?
                                if(count($this->category_list) > 0){
                                    foreach($this->category_list as $key => $value){?>
                                        <option value="<?=$value['category_id']?>" <?if($this->row['category_id'] == $value['category_id']){echo ' selected';}?>><?=$value['category_name']?></option>
                                        <?
                                    }
                                }?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label" for="brand_id">Бренд</label>
                        <div class="form-control no-padding">
                            <select class="form-control" id="brand_id" name="brand_id">
                                <option value="0">Выберите бренд</option>
                                <?
                                if(count($this->brand_list) > 0){
                                    foreach($this->brand_list as $key => $value){?>
                                        <option value="<?=$value['brand_id']?>" <?if($this->row['brand_id'] == $value['brand_id']){echo ' selected';}?>><?=$value['brand_name']?></option>
                                        <?
                                    }
                                }?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label " for="barcode">Штрихкод</label>
                        <input type="text" id="barcode" placeholder="Штрихкод" class="form-control" value="<?=$this->row['barcode']?>" name="barcode">
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label " for="price">Цена</label>
                        <input type="text" id="price" placeholder="Цена" class="form-control" value="<?=$this->row['price']?>" name="price">
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <button type="submit" class="btn btn-sm btn-success">
                    <i class="ace-icon fa fa-check"></i>
                    Сохранить
                </button>
            </div>
        </form>
        <div class="clearfix"></div>

    </div>
    <div class="tab-pane" id="characteristics1">
        <form id="stack_form">
            <div class="form-group">
                <input type="hidden" value="<?=$this->product_id?>" name="product_id" class="product_id">
                <div onclick="addNewCharacteristicByProduct()" style="cursor: pointer;">
                    <i class="fa fa-plus-circle green" style="float: left; margin: 7px 0px 0px 5px;"></i>
                    <p style="float: left; margin-top: 4px; margin-left: 10px">Добавить стеллаж</p>
                </div>
                <div class="clearfix"></div>
                <?if(count($this->product_stack_list) > 0)
                {
                    foreach ($this->product_stack_list as $key1 => $stack){
                    ?>
                        <div style="padding: 0px; margin-top: 10px;" class="product-characteristic-item">
                            <div class="col-sm-6 col-lg-3 col-md-4 col-xs-6 control-label no-padding-right" style="margin-right: 10px;">
                                <select name="stack_id[<?=$stack['product_stack_id']?>]" class="product_stack form-control" style="margin-bottom: 0px;" required>
                                    <option value="0">Выберите стеллаж</option>
                                    <?  if(count($this->stack_list) > 0){
                                        foreach($this->stack_list as $key => $stack_list){ ?>
                                            <option value="<?=$stack_list['stack_id']?>" <?if($stack_list['stack_id'] == $stack['stack_id']){?>selected<?}?>><?=$stack_list['stack_num']?></option>
                                        <?      }
                                    }
                                    ?>
                                </select>
                            </div>
                            <div class="col-lg-2" style="display: flex; align-items: center; justify-content: space-between; flex-wrap: nowrap; margin-bottom: 5px;">
                                <div class="value col-sm-12 col-lg-12 col-md-12 col-xs-12" style="display: none">
                                </div>
                                <i class="fa fa-remove red" style="float: left; cursor: pointer;" onclick="deleteProductCharacteristic(this, <?=$stack['product_stack_id']?>)"></i>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <?
                    }
                }?>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </form>
        <div style="margin-top: 10px;">
            <button type="button" class="btn btn-sm btn-success" name="upd_product" onclick="updProductChar()">
                <i class="ace-icon fa fa-check"></i>
                Сохранить
            </button>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<input type="hidden" id="counter" value="1">
<div class="product-characteristic-item-clone" style="display: none;">
    <div class="form-group">
        <div class="col-sm-6 col-lg-3 col-md-4 col-xs-6 control-label no-padding-right" style="margin-right: 10px;">
            <input type="hidden" value="0" name="product_stack_id_new[]" class="product_stack_id_new">
            <select name="product_stack_new[]" class="product_stack_new form-control" style="margin-bottom: 0px;" required>
                <option value="0">Выберите стеллаж</option>
                <?  if(count($this->stack_list) > 0){
                    foreach($this->stack_list as $key => $stack_list){ ?>
                        <option value="<?=$stack_list['stack_id']?>"><?=$stack_list['stack_num']?></option>
                    <?      }
                }
                ?>
            </select>
        </div>
        <div class="col-lg-2" style="display: flex; align-items: center; justify-content: space-between; flex-wrap: nowrap; margin-bottom: 5px;">
            <div class="value col-sm-12 col-lg-12 col-md-12 col-xs-12" style="display: none">
            </div>
            <i class="fa fa-remove red" style="float: left; cursor: pointer;" onclick="deleteProductCharacteristic(this,0)"></i>

        </div>
        <div class="clearfix"></div>
    </div>
</div>
<script>
    function addNewCharacteristicByProduct(){
        counter = $("#counter").val();
        a = $(".product-characteristic-item-clone").clone();
        a.removeClass("product-characteristic-item-clone");
        a.addClass("product-characteristic-item");
        a.find(".product_stack_id_new").attr("name","product_stack_id_new[" + counter +"]");
        a.find(".product_stack_new").attr("name","product_stack_new[" + counter +"]");
        a.css("display","block");
        $("#stack_form").append(a);
        counter++;
        $("#counter").val(counter);
    }
    function updProductChar(){
        $.ajax({
            type: 'POST',
            data:   $("#stack_form").serialize(),
            url: "/dict/product-list/mode/upd-stack/",
            success: function(data){
                if(data.result['status'] == false){
                    Notify.generate('Ошибка', '', 3);
                    alert(data.result['error']);
                }
                else{
                    Notify.generate('Продукт отредактирован', '', 1);
                     location.reload();
                }
            }
        });
    }
    function deleteProductCharacteristic(ob, product_stack_id){
        $(ob).closest(".product-characteristic-item").remove();

        if(product_stack_id > 0){
            $.ajax({
                type: 'POST',
                url: "/dict/product-list/mode/delete-stack/product_stack_id/"+ product_stack_id + "/",
                success: function(data){
                    if(data.result == false){
                        Notify.generate("Ошибка", '', 3);
                    }
                    else{
                        Notify.generate("Характеристика успешно удалена", '', 1);
                    }
                }
            });
        }
    }
</script>