<div class="page-header">
    <h1 class="pull-left">Ведение товаров</h1>
    <div class="btns-block pull-left">
        <a href="/dict/product-edit/product_id/0/" class="btn btn-xs btn-primary" >Добавить товар</a>
    </div>
    <ul class="list-unstyled spaced list-inline pull-right no-margin-bottom">
        <li class="no-margin">
            <div class="action-buttons" title="Вычислить оптимальное количество заказа">
                <a class="blue" href="javascript:void(0);">
                    <i class="ace-icon fa fa-search-plus bigger-130"></i>
                </a>
                Вычислить ОКЗ
            </div>
        </li>
        <li class="no-margin">
            <div class="action-buttons">
                <a class="blue" href="javascript:void(0);">
                    <i class="ace-icon fa fa-plus-circle bigger-130"></i>
                </a>
                Добавить кол-во
            </div>
        </li>
        <li class="no-margin">
            <div class="action-buttons">
                <a class="red" href="javascript:void(0);">
                    <i class="ace-icon fa fa-trash-o bigger-130"></i>
                </a>
                Удаление товара
            </div>
        </li>
    </ul>
    <div class="clearfix"></div>
</div>
<div class="clearfix"></div>
<div class="pull-left margin-right-5" style="width: 170px; margin-right: 5px">
    <select class="chosen-select" style="width: 100px" id="category_id" name="category_id" data-placeholder="Категории...">
        <option value="0"></option>
        <?php foreach ($this->category_list as $key => $value){ ?>
            <option value="<?=$value['category_id'];?>"><?=$value['category_name'];?></option>
        <?}?>
    </select>
</div>
<div class="pull-left margin-right-5" style="width: 170px; margin-right: 5px">
    <select class="chosen-select" style="width: 100px" id="product_type_id" name="product_type_id" data-placeholder="Типы товаров...">
        <option value="0"></option>
        <?php foreach ($this->product_type_list as $key => $value){ ?>
            <option value="<?=$value['product_type_id'];?>"><?=$value['product_type_name'];?></option>
        <?}?>
    </select>
</div>
<div class="pull-left margin-right-5" style="width: 170px; margin-right: 5px">
    <select class="chosen-select" style="width: 100px" id="brand_id" name="brand_id" data-placeholder="Бренды...">
        <option value="0"></option>
        <?php foreach ($this->brand_list as $key => $value){ ?>
            <option value="<?=$value['brand_id'];?>"><?=$value['brand_name'];?></option>
        <?}?>
    </select>
</div>
<div class="clearfix"></div>
<div class="hr hr-10 dotted hr-double"></div>

<div id="table">
    <input type="hidden" value="" class="hidden-product-id">
    <!-- table -->
</div>


<div id="modal" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header no-padding">
                <div class="table-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        <span class="white">&times;</span>
                    </button>
                    Редактирование кол-во
                </div>
            </div>
            <div id="modal_body"></div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>


<script>
    $(document).ready(function() {
        productListTable();
        $('#category_id').on('change', function () {
            $("#table").empty();
            $("#table").load("/dict/product-list-form/category_id/" + $("#category_id").val() +"/brand_id/" + $("#brand_id").val() + "/product_type_id/" + $("#product_type_id").val()+'/');
        });

        $('#brand_id').on('change', function () {
            $("#table").empty();
            $("#table").load("/dict/product-list-form/category_id/" + $("#category_id").val() +"/brand_id/" + $("#brand_id").val() + "/product_type_id/" + $("#product_type_id").val()+'/');
        });

        $('#product_type_id').on('change', function () {
            $("#table").empty();
            $("#table").load("/dict/product-list-form/category_id/" + $("#category_id").val() +"/brand_id/" + $("#brand_id").val() + "/product_type_id/" + $("#product_type_id").val()+'/');
        });

        $(".chosen-select").chosen({
            allow_single_deselect: true,
            no_results_text: "Ничего не найдено..."
        });
    });
    function productListTable(){
        $.ajax({
            type: 'POST',
            url: "/dict/product-list-form/",
            success: function(data){
                $('#table').html(data);
            }
        });
    }
    function delProduct(product_id, ob){
        if (!confirm("Вы действительно хотите удалить товар?")) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/dict/product-list/mode/delete/product_id/" + product_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    Notify.generate('Ошибка', '', 3);
                }
                else{
                    Notify.generate('Товар успешно удален', '', 1);
                    $(ob).closest("tr").remove();
                }
            }
        });
    }
    function addCnt(product_id){
        $("#modal_body").empty();
        $.ajax({
            type: 'POST',
            url: "/dict/product-cnt-edit/product_id/" + product_id + "/",
            async: true,
            success: function(data){
                $("#modal_body").html(data);
            }
        });
        $(".modal").modal('show');
    }
    function countOpt(product_id){
        $("#modal_body").empty();
        $.ajax({
            type: 'POST',
            url: "/dict/product-opt-lot/product_id/" + product_id + "/",
            async: true,
            success: function(data){
                $("#modal_body").html(data);
            }
        });
        $(".modal").modal('show');
    }
</script>