<script src="/version_2.0/ace_admin/assets/js/utils.js?v=7"></script>
<div class="modal-body" id="modal_body">
    <form method="post" id="form_id">
        <input type="hidden" value="<?=$this->product_id?>" id="product_id" name="product_id">
        <div class="col-sm-12">
            <div class="form-group">
                <label class="control-label " for="fio">Начало даты</label>
                <input class="form-control date-picker" type="text" name="date_begin" id="date_begin" placeholder="С" data-date-format="dd/mm/yyyy" autocomplete="off">
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="form-group">
                <label class="control-label " for="fio">Конец даты</label>
                <input class="form-control date-picker" type="text" name="date_end" id="date_end" placeholder="По" data-date-format="dd/mm/yyyy" autocomplete="off">
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="form-group">
                <p class="green" id="success" style="display: none">ОКЗ получен</p>
                <p class="red" id="danger" style="display: none">Нет данных в базе</p>
                <label class="control-label" for="fio">Количество</label>
                <input type="hidden" id="status" name="status" value="0">
                <input type="text" id="amount" placeholder="Количество" class="form-control" name="amount">
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer no-margin-top">
    <button type="button" class="btn btn-sm btn-success" name="upd_amount" onclick="saveToLot()">
        <i class="ace-icon fa fa-check"></i>
        Сохранить
    </button>
    <button class="btn btn-sm btn-primary" onclick="getOptLotCnt()">
        <i class="ace-icon fa fa-get-pocket"></i>
        Рассчитать
    </button>
</div>
<script>
    function saveToLot() {
        var status = $('#status').val();
        if (status == 1){

            var send_data = $('#form_id').serializeArray();
            $.ajax({
                type: 'POST',
                data: send_data,
                url: "/dict/product-list/mode/upd-lot/",
                success: function(data){
                    if(data.result['status'] == false){
                        Notify.generate('Ошибка', '', 3);
                    }
                    else{
                        Notify.generate('Лот добавлен', '', 1);
                        $(".modal").modal('hide');
                        // stackListForm();
                    }
                }
            });
        }else{
            Notify.generate('Нет данных', '', 3);
        }
    }
    function getOptLotCnt() {
        var date_begin = $("#date_begin").val();
        var date_end = $("#date_end").val();
        var product_id = $("#product_id").val();
        $.ajax({
            type: 'POST',
            data: {product_id:product_id, date_begin:date_begin, date_end:date_end},
            url: "/dict/product-list/mode/get-opt-lot/",
            success: function(data){
                if(data.result['status'] == false){
                    Notify.generate('Ошибка', '', 3);
                }
                else{
                    Notify.generate('ОКЗ получен', '', 1);
                    $("#amount").val(data.result['value']);
                    if(data.result['value'] > 0){
                        $('#success').show();
                        $('#danger').hide();
                        $('#status').val(1);
                    } else{
                        $('#success').hide();
                        $('#danger').show();
                        $('#status').val(0);
                    }
                }
            }
        });
    }
</script>