<style>
    td {
        vertical-align: baseline;
    }
</style>
<div class="page-header">
    <h1 class="pull-left">Ведение заказов</h1>
    <?if($this->status_id == 1){?>
        <div class="btns-block">
            <a href="/dict/request-edit/request_id/0/status_id/<?=$this->status_id?>" class="btn btn-xs btn-primary" >Новый заказ</a>
        </div>
    <?}?>
    <div class="clearfix"></div>
</div>
<div class="clearfix"></div>
<!--<div class="col-xs-12 col-sm-12 col-md-5 col-lg-4" style="float: right; margin-bottom: 10px;">-->
<!--    <form method="post" style="float: right;">-->
<!--        <div style="float:left; margin-right: 3px;">-->
<!--            --><?// if($this->status_id == 1 || $this->status_id == 3){ ?>
<!--                <a href="/dict/request-list/mode/appendix1/status_id/--><?//=$this->status_id?><!--/&date_begin=--><?//=$this->date_begin?><!--&date_end=--><?//=$this->date_end?><!--/">-->
<!--                    <input type="button" class="btn btn-primary" value="Выгрузка в doc">-->
<!--                </a>-->
<!--            --><?// }?>
<!--        </div>-->
<!--        <div class="clearfix"></div>-->
<!--    </form>-->
<!--</div>-->
<form id="form1">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6" style="">
			<div class="col-lg-5 col-md-6 col-sm-6 col-xs-12">
				<label class="control-label">По периоду</label>
				<div class="clearfix"></div>
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style="padding-left: 0;">
					<input class="form-control date-picker" type="text" name="date_begin" id="start_date" placeholder="С" data-date-format="dd/mm/yyyy" autocomplete="off" value="<?=$this->date_begin?>">
				</div>
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" style="padding-right: 0;">
					<input class="form-control date-picker" type="text" name="date_end" id="end_date" placeholder="По" data-date-format="dd/mm/yyyy" autocomplete="off" value="<?=$this->date_end?>">
				</div>
			</div>
        <div class="col-lg-3 col-md-6 col-sm-4 col-xs-12">
            <label class="control-label">Адрес</label>
            <div class="clearfix"></div>
            <input type="text" class="form-control" name="address" value="<?=$this->address?>" placeholder="Адрес"  autocomplete="off">
        </div>
        <div class="col-lg-4 col-md-6 col-sm-4 col-xs-12" style="display: none">
            <label class="control-label">Ном.телефона</label>
            <div class="clearfix"></div>
            <input type="text" class="form-control" name="telephone" id="telephone" value="<?=$this->telephone?>" placeholder="Ном.телефона"  autocomplete="off">
        </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12" style="margin-top: 26px;">
        <a>
            <button type="submit" class="btn btn-sm btn-primary" name="submit" ">
            <i class="ace-icon fa fa-search"></i>
            Поиск
            </button>
        </a>
        <a href="/dict/request-list/status_id/<?=$this->status_id?>/">
            <button type="button" class="btn btn-sm btn-primary" name="resetSearch"">
            <i class="ace-icon fa fa-refresh"></i>
            Сбросить
            </button>
        </a>
        <?if($this->status_id != 2){?>
            <a style="float:right;" href="/dict/request-list/mode/appendix1/status_id/<?=$this->status_id?>/date_begin/<?=$this->date_begin?>/date_end/<?=$this->date_end?>/address/<?=$this->address?>/telephone/<?=$this->telephone?>/">
                <button type="button" class="btn btn-sm btn-primary" name="resetSearch"">
                <i class="ace-icon fa fa-download"></i>
                Выгрузка в doc
                </button>
            </a>
        <?}?>
    </div>
</form>
<div class="clearfix"></div>
<div class="hr hr-10 dotted hr-double"></div>
<div class="table-responsive">
    <table class="table-local table-striped table-bordered hover-table no-margin-bottom no-border-top">
        <thead>
        <tr>
            <th>ID</th>
            <th>Адрес</th>
            <th>Телефон</th>
            <th>Дата доставки</th>
            <th>Оператор/Комментарий</th>
            <th>Товары</th>
            <th>Сумма</th>
            <th>Курьер</th>
            <th>Изменить статус</th>
        </tr>
        </thead>
        <tbody>
        <?
            echo $this->partialLoop('dict/request-list-form.phtml', $this->paginator);
        ?>
        </tbody>
    </table>
    <div style="float: right">
        <?=$this->paginationControl($this->paginator, 'Sliding', 'dict/pagination.phtml');?>
    </div>


        </tbody>
    </table>
</div>

<script>
    $(document).ready(function() {
        $("#telephone").mask("+7(999) 999 99 99");
    });

    function showTr(ob){
        if($(ob).closest(".product_table_list").find(".hidden-product").css("display") == "none"){
            $(ob).closest(".product_table_list").find(".hidden-product").css("display","table-cell");
            $(ob).closest("td").find(".tr-hide-icon").show();
            $(ob).closest("td").find(".tr-show-icon").hide();
        }
        else{
            $(ob).closest(".product_table_list").find(".hidden-product").css("display","none");
            $(ob).closest("td").find(".tr-show-icon").show();
            $(ob).closest("td").find(".tr-hide-icon").hide();
        }
    }
    function setRequestCourier(request_id, user_id, ob){
        $.ajax({
            type: 'POST',
            url: "/dict/index-json/mode/change-request-courier/request_id/"+request_id+"/user_id/"+user_id+"/",
            success: function(data){
                if(data.result == false){
                    Notify.generate("Ошибка при изменений");
                }else{
                    Notify.generate("Заявка успешно изменена");
                    $(ob).closest("td").find(".operation-classes").attr("disabled", false);
                    $(ob).attr("disabled", true);
                }
            }
        });
    }
    function changeRequestStatus(request_id, status_id, ob){
        $.ajax({
            type: "POST",
            url: "/dict/index-json/mode/change-request-status/request_id/"+request_id+"/status_id/"+status_id+"/",
            success: function (data) {
                if(data.result == false){
                    Notify.generate("Ошибка при изменении статуса");
                }else{
                    Notify.generate("Статус успешно изменен");
                    $(ob).closest("td").find(".operation-classes").attr("disabled", false);
                    $(ob).attr("disabled", true);
                }
            }
        });
    }
</script>