<style>
    .left-block{
        width: 100px;;
    }
    .right-block input{
        margin-bottom: 0px;
    }
    .error{
        font-size: 12px;
        margin-bottom: 0px;
    }
    .right-block label{
        margin-left: 90px;
    }
    .count {
        background: none repeat scroll 0 0 rgba(0, 0, 0, 0) !i  mportant;
        border: 0 none !important;
        color: #000000;
        font-size: 12px !important;
        line-height: 14px;
        margin: 3px 0 4px !important;
        outline: medium none;
        padding: 0 !important;
        text-align: center;
        width: 23px;
        float: left;
        overflow: hidden;
    }
    .fa-plus, .fa-minus {
        display: block;
        height: 19px;
        top: 1px;
        width: 17px;
        float: left;
        cursor: pointer;
    }
    .fa-minus{
        margin-left: 2px;
    }
    .fa-minus:before,.fa-plus:before {
        content: "";
    }
    .datapicker_block label{
        float: right;
        margin-left: 0px;
        margin-right: 35px;
    }
</style>
<div class="page-header">
    <h1 class="pull-left">Редактирование заказа</h1>
    <div class="clearfix"></div>
</div>
<div class="clearfix"></div>
<form method="post" id="form_id">
    <input type="hidden" value="<?=$this->request_id?>" name="request_id">
    <input type="hidden" value="<?=$this->status_id?>" id="status_id" name="status">
    <div class="col-sm-6">
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label " for="fio">Адрес</label>
                <input type="text" required id="address" placeholder="Адрес" class="form-control" name="address" value="<?=$this->row['address']?>">
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label " for="fio">Телефон</label>
                <input type="text" required id="telephone" placeholder="Телефон" class="form-control" name="telephone" value="<?=$this->row['telephone']?>">
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label " for="request_date">Дата</label>
                <input class="form-control date-picker" required type="text" name="request_date" id="request_date" placeholder="Дата" data-date-format="dd/mm/yyyy" autocomplete="off" value="<?=$this->row['request_date']?>">
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label" for="brand_id">Курьер</label>
                <div class="form-control no-padding">
                    <select class="form-control" id="courier_id" name="courier_id">
                        <option value="0">Выберите курьера</option>
                        <?
                        if(count($this->courier_list) > 0){
                            foreach($this->courier_list as $key => $value){?>
                                <option value="<?=$value['employee_id']?>" <?if($this->row['courier_id'] == $value['employee_id']){echo ' selected';}?>><?=$value['fio']?></option>
                                <?
                            }
                        }?>
                    </select>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label" for="comment">Комментарии оператора</label>
                <div class="no-padding">
                    <textarea name="comment" id="comment" style="width: 233px; height: 80px;"><?=$this->row['comment']?></textarea>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>

    <div class="row-fluid">
        <div class="widget-box">
            <div class="widget-header widget-header-flat">
                <h4 class="smaller">
                    Продукты заявки
                </h4>
            </div>
            <?  $ob = new Application_Model_DbTable_Dict();?>

            <div class="widget-body">
                <div class="widget-main">
                    <table class="table table-striped table-bordered table-hover product_table_list">
                        <?
                        $request_item = $ob->request_product_read($this->row['request_id'])['value'];
                        //                            var_dump($request_item);
                        $i = 0;
                        $sum = 0;
                        foreach($request_item as $key => $request_product) {
                            $i++;
                            $sum += $request_product['amount'] * $request_product['price'];
                            ?>

                            <tr class="request-product-tr">
                                <td style="width: 1200px;">
                                    <input type="hidden" value="<?=$request_product['request_product_id']?>" name="request_product_id[<?=$request_product['request_product_id']?>]">
                                    <input type="hidden" value="<?=$request_product['product_id']?>" name="product_id[<?=$request_product['request_product_id']?>]">
                                    <p><?=$request_product['product_name']?></p>
                                </td>
                                <td style="width: 100px;">
                                    <div style="background: url('/css/image/icons3.png') repeat scroll 0 0 rgba(0, 0, 0, 0);  background-position: 112px 39px; height: 21px; width: 62px;display: inline-block; float: left;">
                                        <a class="fa fa-minus" onclick="decrementCount(this)"></a>
                                        <input class="count count_text product-unit-value" type="text" name="amount[<?=$request_product['request_product_id']?>]" value="<?=$request_product['amount']?>" onkeyup="checkToNum(this)">
                                        <a class="fa fa-plus" onclick="incrementCount(this)"></a>
                                    </div>
                                    <p style="float:left;margin-left:5px; margin-top:3px;">шт.</p>
                                    <div class="clearfix"></div>
                                </td>
                                <td style="width: 150px;"><input type="text" value="<?=$request_product['price']?>" name="price[<?=$request_product['request_product_id']?>]" style="width: 100px;" class="product-price-value" onkeyup="checkToNum(this)"> тг.</td>
                                <td style="width: 50px;">
                                    <i class="fa fa-remove red" style="cursor: pointer" onclick="deleteProductFromRequest(<?=$request_product['request_product_id']?>,<?=$request_product['amount']?>, <?=$request_product['product_id']?>, this)"></i>
                                </td>
                            </tr>

                        <? } ?>
                        <tr id="last_tr_sum">
                            <td colspan="4" style="text-align: right; padding-right: 20px; font-size: 14px;" id="total_sum"><b>Сумма:</b> <span id="abs_sum"><?=$sum?></span> тг.</td>
                            <input type="hidden" name="sum" id="sum" value="<?=$sum?>">
                        </tr>
                    </table>

                    <div>
                        <div style="float: left; padding-top: 5px; margin-right: 5px;">
                            <i class="fa fa-plus-circle green " aria-hidden="true"></i>
                        </div>
                        <div style="float: left; margin-right: 5px;">
                            <input type="text" id="new_product_input2" name="new_product_add" class="ui-autocomplete-input" autocomplete="off">
                        </div>
                        <div class="clearfix"></div>
                    </div>

                    <div style="float: right;">
                        <a href="/dict/request-list/status_id/1/">
                            <input type="button" class="btn btn-danger" value="Назад">
                        </a>
                        <input type="button" class="btn btn-primary" value="Сохранить" onclick="updRequest()">
                    </div>
                    <div class="clearfix"></div>

                </div>
            </div>
        </div>
    </div>
</form>
<div class="hidden clone-product-tr">
    <table>
        <tbody>
        <tr class="request-product-tr">
            <td style="width: 1200px;">
                <input type="hidden" value="" name="product_id_new[]" class="product-id-hidden">
                <p class="product-name"></p>
            </td>
            <td style="width: 100px;">
                <div style="background: url('/css/image/icons3.png') repeat scroll 0 0 rgba(0, 0, 0, 0);  background-position: 112px 39px; height: 21px; width: 62px;display: inline-block; float: left;">
                    <a class="fa fa-minus" onclick="decrementCount(this)"></a>
                    <input class="count count_text product-unit-value" type="text" name="unit_new[]" value="1" onkeyup="checkToNum(this)">
                    <a class="fa fa-plus" onclick="incrementCount(this)"></a>
                </div>
                <p style="float:left;margin-left:5px; margin-top:3px;">шт.</p>
                <div class="clearfix"></div>
            </td>
            <td style="width: 150px;"><input type="text" class="price-input" value="" name="price_new[]" style="width: 100px;" onkeyup="checkToNum(this)"> тг.</td>
            <td style="width: 50px;">
                <i class="fa fa-remove red" style="cursor: pointer" onclick="deleteProductFromRequest(null,this)"></i>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<script>
    $(document).ready(function() {
        $("#telephone").mask("+7(999) 999 99 99");

        $("#new_product_input2").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: "/dict/request-edit/mode/get-products/",
                    data: {
                        product_name: request.term
                    },
                    success: function (data) {
                        response($.map(data.product_list, function (item) {
                            return {
                                label: item.product_name,
                                value: item.product_name,
                                key: item.product_id,
                                price: item.price
                            }
                        }));
                    }
                });
            },
            minLength: 2,
            select: function (event, ui) {
                a = '';
                a = $('.clone-product-tr').clone();
                $(a).find(".product-id-hidden").attr("value", ui.item.key);
                $(a).find(".product-name").html(ui.item.value);

                $(a).find(".price-input").attr("value", ui.item.price);

                $(a).find(".price-input").addClass("product-price-value");
                $(a).find(".unit-input").addClass("product-unit-value");
                $(a).find(".unit-input").removeClass("unit-input");
                a = $(a).find("tbody").html();
                $(a).insertBefore('#last_tr_sum');
                //$(".product_list_table").find("tbody").append(a);
                $(this).val("");
                changeTotalSum();
                return false;
            }
        });
    });

    function checkProductSelected(){
        var new_product_input_len = myTrim($("#new_product_input").val());
        // if(new_product_input_len.length > 0){
        // }
        // else{
        //     $("#product_id").attr("value","");
        // }
    }

    function myTrim(x) {
        return x.replace(/^\s+|\s+$/gm,'');
    }
    function deleteProductFromRequest(request_product_id, amount, product_id,  ob){
        if(request_product_id > 0){
            $.ajax({
                type: 'POST',
                url: "/dict/request-edit/mode/delete-request-product/request_product_id/"+request_product_id + "/amount/"+ amount +"/product_id/"+ product_id +"/",
                success: function(data){
                    if(data.result == false){
                        Notify.generate("Ошибка", '', 3);
                    }
                    else{
                        Notify.generate("Продукт удален", '', 1);
                    }
                }
            });
        }
        $(ob).closest(".request-product-tr").remove();
        changeTotalSum();
    }

    function changeTotalSum(){
        total_sum = 0;
        $(".product-unit-value").each(function() {
            unit = parseFloat($(this).val());
            if(unit !== parseFloat(unit)){
                unit = 0;
            }
            price = parseFloat($(this).closest("tr").find(".product-price-value").val());
            if(price !== parseFloat(price)){
                price = 0;
            }
            total_sum += unit*price;
        });
        $("#total_sum").html("<b>Сумма:</b> <span id='abs_sum'> "+ total_sum + "</span> тг.");
        $("#sum").val(total_sum);
    }
    function incrementCount(ob){
        count = $(ob).closest("td").find("input").val();
        count++;
        $(ob).closest("td").find("input").attr("value",count);
        changeTotalSum();
    }
    function decrementCount(ob){
        count = $(ob).closest("td").find("input").val();
        count--;
        if(count < 1){
            $(ob).closest("td").find("input").attr("value",1);
            count = 1;
        }
        else{
            $(ob).closest("td").find("input").attr("value",count);
        }
        changeTotalSum();
    }
    function checkToNum(ob){
        if($(ob).val() > 0){
        }
        else{
            $(ob).val(1);
        }
        changeTotalSum();
    }
    function setHiddenLineId(line_id){
        $(".hidden-line-id").attr("value",line_id);
    }
    function clearHiddenLineId(){
        $(".hidden-line-id").attr("value",-1);
    }
    function updRequest(){
        var status_id = $('#status_id').val();
        $.ajax({
            type: 'POST',
            data:   $("#form_id").serialize(),
            url: "/dict/request-edit/mode/upd-request/",
            success: function(data){
                if(data.result['status'] == false){
                    Notify.generate('Ошибка', '', 3);
                    alert(data.result['error']);
                }
                else{
                    Notify.generate('Заявка отредактирован', '', 1);
                    location.assign('/dict/request-list/status_id/'+status_id+'/');
                }
            }
        });
    }
</script>