
<div class="page-header">
    <h1>Типы запросов</h1>
</div>

<div class="table-responsive">
    <table class="table-local table-striped table-bordered hover-table no-margin-bottom no-border-top">
        <thead>
        <tr>
            <th>ID</th>
            <th>Родитель</th>
            <th>Наименование</th>
            <th>Код</th>
            <th>Ссылка</th>
            <th>
                <div class="action-buttons">
                    <a class="blue" href="/dict/request-type-edit/request_type_id/0/">
                        <i class="ace-icon fa fa-plus-circle bigger-130"></i>
                    </a>
                </div>
            </th>
        </tr>
        </thead>
        <tbody>
        <?foreach ($this->row  as $key => $value)
        {?>
            <tr>
                <td class="text-right"><a href="/dict/request-type-edit/request_type_id/<?=$value['request_type_id']?>/"><?=$value['request_type_id']?></a></td>
                <td class="text-left"><?=$value['parent']?></td>
                <td class="text-left"><?=$value['request_name']?></td>
                <td class="text-left"><?=$value['request_code']?></td>
                <td class="text-left"><a href="<?=$value['item_href']?>" target="_blank"><?=$value['item_href']?></a></td>
                <td class="text-center">
                    <div class="action-buttons">
                        <a class="red" href="javascript:void(0);" onclick="delType(<?=$value['request_type_id']?>, this)">
                            <i class="ace-icon fa fa-trash-o bigger-130"></i>
                        </a>
                    </div>
                </td>
            </tr>
            <?
        }
        ?>

        </tbody>
    </table>
</div>
<script>
    function delType(request_type_id, ob){
        if (!confirm('Вы действительно хотите удалить этот запрос?')) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/dict/request-type-list/mode/delete/request_type_id/" + request_type_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    Notify.generate('Ошибка', '', 3);
                    alert(data.result['error']);
                }
                else{
                    Notify.generate('Запрос удален', '', 1);
                    $(ob).closest("tr").remove();
                }
            }
        });

    }
</script>