<div class="page-header">
    <h1 class="pull-left">Редактирование типа запроса</h1>
    <div class="clearfix"></div>
</div>
<div class="col-lg-4">
    <?
    if (isset($this->error)) {?>
        <div class="alert alert-danger">
            <?=$this->error?>
        </div>
        <?
    }?>
    <form method="post" id="form_id">
        <input type="hidden" value="<?=$this->request_type_id?>" name="request_type_id" id="request_type_id">
        <div class="form-group position-relative">
            <label class="control-label " for="banner_name">Наименование</label>
            <input type="text" id="request_name" placeholder="Наименование" class="form-control" value="<?=$this->row['request_name']?>" name="request_name">
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
        <div class="form-group position-relative">
            <label class="control-label " for="banner_name">Код</label>
            <input type="text" id="request_code" placeholder="Код" class="form-control" value="<?=$this->row['request_code']?>" name="request_code">
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
        <div class="form-group">
            <label class="control-label " for="provider_id">Родитель</label>
            <div class="form-control no-padding">
                <select class="chosen-select form-control" id="request_type_pid" data-placeholder="Выберите тип..." name="request_type_pid">
                    <option value="0"> </option>
                    <?
                    foreach ($this->request_type_list as $key => $value){?>
                        <option value="<?=$value['request_type_id']?>" <?if($this->row['request_type_pid'] == $value['request_type_id']){echo ' selected';}?>><?=$value['request_name']?></option>
                        <?
                    }
                    ?>
                </select>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>

        <div class="form-group position-relative">
            <label class="control-label " for="banner_name">Ссылка</label>
            <input type="text" id="item_href" placeholder="Ссылка" class="form-control" value="<?=$this->row['item_href']?>" name="item_href">
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>

        <div class="form-group">
            <label class="control-label " for="message_text">Текст сообщения</label>
            <textarea class="form-control" name="message_text" style="height: 100px; overflow: hidden; overflow-wrap: break-word; resize: horizontal;" id="message_text" placeholder="Текст сообщения"><?=$this->row['message_text']?></textarea>
            <div class="clearfix"></div>
        </div>

        <div class="form-group">
            <label class="control-label " for="upload">Файл</label>
            <a href="<?=$value['doc_url']?>" target="_blank"><?=$value['doc_name']?></a>
            <div class="form-control no-padding">
                <input type="file" name="request_document" id="request_document">
            </div>
            <div class="clearfix"></div>
        </div>

        <button type="button" onclick="upd()" style="margin-left: 5px;" class="btn btn-success pull-right">Сохранить</button>

        <a href="/dict/request-type-list/">
            <button type="button" class="btn btn-danger pull-right">Назад</button>
        </a>
        <div class="clearfix"></div>
    </form>
</div>

<script>
    $(document).ready(function() {

    });
    function upd(){
        var fd = new FormData($("#form_id")[0]);
        $.ajax({
            type: 'POST',
            url: "/dict/request-type-edit/mode/upd/",
            data: fd,
            success: function(data){
                if(data.result['status'] == false){
                    Notify.generate('Ошибка', '', 3);
                    alert(data.result['error']);
                }else{
                    Notify.generate('Успех', '', 1);
                    // document.location.reload();
                    window.location='/dict/request-type-list/'
                }
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }


</script>