
<div class="page-header">
    <h1>Запросы от пользователей</h1>
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
        <thead>
        <tr>
            <th>ID</th>
            <th>Тип запроса</th>
            <th>Пользователь</th>
            <th>Ответ</th>
            <th>Дата запроса</th>
        </tr>
        </thead>
        <tbody>
            <?foreach ($this->row as $key => $value){?>
                <tr>
                    <td class="text-right"><?=$value['request_id']?></td>
                    <td class="text-left"><?=$value['request_name']?></td>
                    <td class="text-left"><?=$value['fio']?></td>
                    <td class="text-left"><?=$value['request_answer']?></td>
                    <td class="text-center"><?=$value['request_date']?></td>
                </tr>
                <?
            }?>
        </tbody>
    </table>
</div>
<script>
    function delType(request_type_id, ob){
        if (!confirm('Вы действительно хотите удалить этот запрос?')) {
            return false;
        }
        $.ajax({
            type: 'POST',
            url: "/dict/request-type-list/mode/delete/request_type_id/" + request_type_id + "/",
            success: function(data){
                if(data.result['status'] == false){
                    Notify.generate('Ошибка', '', 3);
                    alert(data.result['error']);
                }
                else{
                    Notify.generate('Запрос удален', '', 1);
                    $(ob).closest("tr").remove();
                }
            }
        });

    }
</script>