<div class="widget-box loading-widget" id="sh_module_widget">
    <div class="widget-header">
        <h4 class="widget-title">Стеллажи
            <div class="action-buttons pull-right">
                <a href="javascript:void(0)" onclick="showModal(0)">
                    <i class="fa fa-plus-circle bigger-130" title="Добавить"></i>
                </a>
            </div>
        </h4>
        <div class="widget-toolbar">
            <a data-action="collapse" href="#">
                <i class="ace-icon fa fa-chevron-up"></i>
            </a>
        </div>
    </div>
    <div class="widget-body" style="display: block;">
        <div class="widget-main">
            <div class="table-responsive">
                <table id="stack" class="table table-striped table-bordered hover-table no-margin-bottom no-border-top">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Код</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?
                    if(count($this->row) > 0){
                        foreach ($this->row as $key => $value){?>
                            <tr>
                                <td onclick="showCat(<?=$value['stack_id']?>, this)" class="text-right"><a href="javascript:void(0)" onclick="showModal(<?=$value['stack_id']?>)"><?=$value['stack_id']?></a></td>
                                <td onclick="showCat(<?=$value['stack_id']?>, this)" class="text-left"><?=$value['stack_num']?></td>
                                <td>
                                    <div class="text-center">
                                        <a class="red" href="javascript:void(0);" onclick="delStack(<?=$value['stack_id']?>, this)">
                                            <i class="ace-icon fa fa-trash-o bigger-130"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            <?
                        }
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


