<div class="modal-body" id="modal_body">
    <form method="post" id="form_id">
        <input type="hidden" value="<?=$this->stack_id?>" name="stack_id">
        <div class="col-sm-12">
            <div class="form-group">
                <label class="control-label " for="fio">Номер стеллажа</label>
                <input type="text" id="stack_num" placeholder="Номер стеллажа" class="form-control" value="<?=$this->row['stack_num']?>" name="stack_num">
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </form>
</div>
<div class="modal-footer no-margin-top">
    <button type="button" class="btn btn-sm btn-success" name="upd_stack" onclick="updStack()">
        <i class="ace-icon fa fa-check"></i>
        Сохранить
    </button>
    <button class="btn btn-sm btn-danger" data-dismiss="modal">
        <i class="ace-icon fa fa-times"></i>
        Закрыть
    </button>
</div>
<script>
    function updStack() {
        var send_data = $('#form_id').serializeArray();
        $.ajax({
            type: 'POST',
            data: send_data,
            url: "/dict/stack-edit/mode/upd-stack/",
            success: function(data){
                if(data.result['status'] == false){
                    Notify.generate('Ошибка', '', 3);
                }
                else{
                    Notify.generate('Стеллаж добавлен', '', 1);
                    $(".modal").modal('hide');
                    stackListForm();
                }
            }
        });
    }
</script>