<div class="login-container change-password-form">
    <div class="center">
        <h6>
            <i class="ace-icon fa fa-wrench green"></i>
            <span class="red">Система</span>
            <span class="blue" id="id-text2">склада</span>
        </h6>
    </div>
    <div class="space-6"></div>
    <?
    if (isset($this->row['error'])) {?>
        <div class="alert alert-danger no-margin">
            <?=$this->row['error']?>
        </div>
        <?
    }?>
    <?
    if (isset($this->success_password_change)) {
        if($this->success_password_change == 1){?>
            <div class="alert alert-success text-center no-margin">
                <strong>Пароль успешно изменен</strong>
            </div>
            <?
        }
    }?>
    <div class="position-relative">
        <div id="login-box" class="login-box visible widget-box no-border">
            <div class="widget-body">
                <div class="widget-main">
                    <h4 class="header blue lighter bigger">
                        <i class="ace-icon fa fa-key green"></i>
                        Смена пароля
                    </h4>
                    <div class="space-6"></div>
                    <form method="post">
                        <fieldset>
                            <label class="block clearfix">
                                <span class="block input-icon input-icon-right">
                                    <input type="password" class="form-control" placeholder="Старый пароль" value="<?$this->row['old_password']?>" name="old_password" autocomplete="off" />
                                    <i class="ace-icon fa fa-lock"></i>
                                </span>
                            </label>
                            <label class="block clearfix">
                                <span class="block input-icon input-icon-right">
                                    <input type="password" class="form-control" placeholder="Новый пароль" value="<?$this->row['new_password']?>" name="new_password" autocomplete="off" />
                                    <i class="ace-icon fa fa-lock"></i>
                                </span>
                            </label>
                            <label class="block clearfix">
                                <span class="block input-icon input-icon-right">
                                    <input type="password" class="form-control" placeholder="Подтверждение нового пароля" value="<?$this->row['confirm_new_password']?>" name="confirm_new_password" autocomplete="off" />
                                    <i class="ace-icon fa fa-lock"></i>
                                </span>
                            </label>
                            <div class="space"></div>
                            <div class="clearfix">
                                <button type="submit" class="width-35 pull-right btn btn-sm btn-primary" name="change_password">
                                    <i class="ace-icon fa fa-key"></i>
                                    <span class="bigger-110">Сменить</span>
                                </button>
                            </div>
                            <div class="space-4"></div>
                        </fieldset>
                    </form>
                </div><!-- /.widget-main -->
            </div>
        </div>
    </div>
</div>