<div class="row-fluid">
    <h1 style="padding: 0; margin: 0 8px; font-size: 24px; font-weight: lighter; color: #2679b5;">Дорогой наш клиент, добро пожаловать в Ваш личный кабинет!</h1>
    <div style="font-size: 18px; margin-top: 10px; color: black;  font-family: Georgia,'Bitstream Charter',serif; line-height: 25px;">
        <p style="font-size: 20px; margin-bottom: 0px;">Для чего он нужен?</p>
        <img src="/css/image/img_1.png" style="margin: 10px 0px;">
        <!--        <p style="font-size: 20px; background-color: #f5f5f5; padding: 10px 5px; width: 485px;">1. Заработать бонусы при формировании заказа онлайн.</p>-->
        <p>Формируя заказ через Ваш личный кабинет, Вы автоматически зарабатываете бонусы.</p>
        <p>Как зарабатываются бонусы? От каждой суммы покупки <b style="color: #62A81C;">3%</b> идут в Вашу копилку бонусов.</p>
        <p>Если у Вас накопилось достаточное количество бонусов на нужный товар, то сразу же можно его использовать. <br> К примеру, если Вы накопили бонус равный 700 тенге, то на эту сумму можно бесплатно получить салфетки Муни.</p>
        <p>Бонус распространяется на все товары одной заявки! Поэтому необходимо оформлять отдельную заявку на те товары, <br>которые вы получите за бонусы, и отдельно вторую заявку, на товары которые вы купите в обычном режиме.</p>
        <p>Помните, что бесплатная доставка на адрес осуществляется только при общем заказе более чем на <? if($this->city_id == 93){ ?> 7000 тенге! <? } else {?> 5000 тенге <? } ?></p>
        <img src="/css/image/img_2.png" style="margin: 10px 0px;">
        <!--        <p style="font-size: 20px; background-color: #f5f5f5; padding: 10px 5px; width: 485px;">2. Мониторинг заказов.</p>-->
        <p>Вы всегда можете увидеть: что и когда заказывали, статус текущей заявки и как идет начисление бонусов. <br>Скоро добавится возможность повторить заказ из Вашей истории.</p>
        <img src="/css/image/img_3.png" style="margin: 10px 0px;">
        <!--        <p style="font-size: 20px; background-color: #f5f5f5; padding: 10px 5px; width: 485px;">3. Новости, акции, подарки.</p>-->
        <p style="margin-bottom: 0px;">В дальнейшем будет пополнятся личный кабинет полезной для Вас информацией. Обязательно будем оповещать <br>Вас по почте, а также в социальной сети Instagram.</p>
        <p>По всем вопросам смело обращайтесь к нам! Будем рады Вам помочь!</p>
        <!--        <p>Наши контакты:</p>-->
        <a href="mailto:shopbebek@mail.ru" style="float:left;">
            <img src="/css/image/email_2.png" style="margin-right: 5px; width: 32px; height: 22px;">
        </a>
        <p style="float:left; padding-top:2px;">Email: <a href="mailto:info@bebek.kz">info@bebek.kz</a></p>
        <div class="clearfix"></div>
        <div class="clearfix"></div>
        <a target="_blank" href="javascript:void(0);" title="Instagram" style="float:left; margin-left:4px; margin-top:2px;">
            <img src="/css/image/instagram_logo.png" style="width: 26px; margin-right: 8px; margin-top: 15px;">
        </a>
        <div style="float: left;">
            <p style="float: left; padding-top: 4px; margin: 0;">Instagram Нур-Султан: <a target="_blank" href="https://www.instagram.com/bebek_astana/" title="Instagram">instagram.com/bebek_astana</a></p>
            <div class="clearfix"></div>
            <p style="float: left; padding-top: 4px;">Instagram Алматы: <a target="_blank" href="https://www.instagram.com/bebek_almaty/" title="Instagram">instagram.com/bebek_almaty</a></p>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
        <p style="font-size: 24px; font-weight: bold; margin-top: 20px; margin-bottom: 0px;">Приятных Вам покупок!</p>
        <p>Всегда Ваш bebek.kz</p>
    </div>
</div>